---
OrdererOrgs:
-   Domain: example.com
    Name: orderer
    Specs:
    -   Hostname: orderer
    -   Hostname: orderer2
    -   Hostname: orderer3
    -   Hostname: orderer4
    -   Hostname: orderer5
PeerOrgs:
-   Domain: org1.example.com
    EnableNodeOUs: true
    Name: org1
    Template:
        Count: 2
    Users:
        Count: 1
-   Domain: org2.example.com
    EnableNodeOUs: true
    Name: org2
    Template:
        Count: 2
    Users:
        Count: 1
